# Chapter 5: Getting Started with Pandas

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

### Series

In [2]:
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values

array([ 4,  7, -5,  3])

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = Series([4, 7, -5, 3], index = ['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2['a']

-5

In [7]:
obj2['d']

4

In [8]:
obj2[obj2 >0]

d    4
b    7
c    3
dtype: int64

In [9]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [10]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [11]:
'b' in obj2

True

In [12]:
'e' in obj2

False

In [13]:
sdata = {'Ohio' : 3500, 'Texas' : 71000, 'Oregon' : 16000, 'Utah' : 5000}
obj3 = Series(sdata)
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = Series(sdata, index = states)
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [15]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [17]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [18]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [19]:
obj3 + obj4

California         NaN
Ohio            7000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [20]:
obj4.name = 'population'
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [21]:
obj4.index.name = 'states'
obj4

states
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [22]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [23]:
data = {'state':['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002],'population':[1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
frame

state  year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2001         2.4
4  Nevada  2002         2.9

In [24]:
DataFrame(data, columns=['year','state', 'population'])

year   state  population
0  2000    Ohio         1.5
1  2001    Ohio         1.7
2  2002    Ohio         3.6
3  2001  Nevada         2.4
4  2002  Nevada         2.9

In [33]:
frame2 = DataFrame(data, columns=['year', 'state', 'population', 'debt'], index=['one','two','three','four','five'])
frame2

year   state  population debt
one    2000    Ohio         1.5  NaN
two    2001    Ohio         1.7  NaN
three  2002    Ohio         3.6  NaN
four   2001  Nevada         2.4  NaN
five   2002  Nevada         2.9  NaN

In [34]:
frame2.columns

Index(['year', 'state', 'population', 'debt'], dtype='object')

In [35]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [36]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [37]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [41]:
frame2.loc['three']

year          2002
state         Ohio
population     3.6
debt           NaN
Name: three, dtype: object

In [29]:
frame2.year>2001

0    False
1    False
2     True
3    False
4     True
Name: year, dtype: bool

In [43]:
frame2['debt'] = 16.5
frame2

year   state  population  debt
one    2000    Ohio         1.5  16.5
two    2001    Ohio         1.7  16.5
three  2002    Ohio         3.6  16.5
four   2001  Nevada         2.4  16.5
five   2002  Nevada         2.9  16.5

In [44]:
frame2['debt'] = np.arange(5.)
frame2

year   state  population  debt
one    2000    Ohio         1.5   0.0
two    2001    Ohio         1.7   1.0
three  2002    Ohio         3.6   2.0
four   2001  Nevada         2.4   3.0
five   2002  Nevada         2.9   4.0

In [45]:
val = Series([-1.2, -1.5, -1.7], index=['two','four','five'])
frame2['debt'] = val
frame2

year   state  population  debt
one    2000    Ohio         1.5   NaN
two    2001    Ohio         1.7  -1.2
three  2002    Ohio         3.6   NaN
four   2001  Nevada         2.4  -1.5
five   2002  Nevada         2.9  -1.7

In [48]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  population  debt  eastern
one    2000    Ohio         1.5   NaN     True
two    2001    Ohio         1.7  -1.2     True
three  2002    Ohio         3.6   NaN     True
four   2001  Nevada         2.4  -1.5    False
five   2002  Nevada         2.9  -1.7    False

In [49]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'population', 'debt'], dtype='object')

In [50]:
pop = {'Nevada':{2001:2.4, 2002:2.9}, 'Ohio':{2000:1.5,2001:1.7,2002:3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [51]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [55]:
frame3.index.name = 'year';
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [56]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [57]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [52]:
big = frame['year']>2001
big

0    False
1    False
2     True
3    False
4     True
Name: year, dtype: bool

## FizzBuzz

In [63]:
for x in range(50):
    if x % 5 == 0 and x%3 == 0:
        print('fizzbuzz')
    elif x % 3 == 0:
        print('fizz')
    elif x % 5 == 0:
        print('buzz')
        continue
    else:    
        print(x)

fizzbuzz
1
2
fizz
4
buzz
fizz
7
8
fizz
buzz
11
fizz
13
14
fizzbuzz
16
17
fizz
19
buzz
fizz
22
23
fizz
buzz
26
fizz
28
29
fizzbuzz
31
32
fizz
34
buzz
fizz
37
38
fizz
buzz
41
fizz
43
44
fizzbuzz
46
47
fizz
49
